<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	<Version>1.0.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<UserSecretsId>07f75224-f5af-47df-b70f-170ed82ee118</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <StartupObject></StartupObject>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Asp.Versioning.Mvc" />
	<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
	<PackageReference Include="Azure.Identity" />
	<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
	<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjectionFixed" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" />
	<PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" />
	<PackageReference Include="Microsoft.AspNetCore.OData" />
	<PackageReference Include="Microsoft.Data.SqlClient" />
	<PackageReference Include="Microsoft.EntityFrameworkCore" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
		<PrivateAssets>all</PrivateAssets>
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
		<PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.Identity.Web" />
	<PackageReference Include="Microsoft.Identity.Web.UI" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoWorkingApp.Application\CoWorkingApp.Application.csproj" />
    <ProjectReference Include="..\CoWorkingApp.Core\CoWorkingApp.Core.csproj" />
    <ProjectReference Include="..\CoWorkingApp.Infrastructure\CoWorkingApp.Infrastructure.csproj" />
    <ProjectReference Include="..\CoWorkingApp.Persistence\CoWorkingApp.Persistence.csproj" />
    <ProjectReference Include="..\CoWorkingApp.Presentation\CoWorkingApp.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\OptionsBuilder\" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties /></VisualStudio></ProjectExtensions>

</Project>
