// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Users.Commands.RegisterUser.CreateUserCommandHandler.#ctor(CoWorkingApp.Core.Contracts.Repositories.IUserRepository,CoWorkingApp.Core.Contracts.UnitOfWork.IUnitOfWork)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Users.Commands.CreateUser.CreateUserCommandHandler.#ctor(CoWorkingApp.Core.Contracts.Repositories.IUserRepository,CoWorkingApp.Core.Contracts.UnitOfWork.IUnitOfWork)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Users.Commands.UpdateUser.UpdateUserCommandHanlder.#ctor(CoWorkingApp.Core.Contracts.Repositories.IUserRepository,CoWorkingApp.Core.Contracts.UnitOfWork.IUnitOfWork)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Users.Commands.UpdateUser.UpdateUserCommandHandler.#ctor(CoWorkingApp.Core.Contracts.Repositories.IUserRepository,CoWorkingApp.Core.Contracts.UnitOfWork.IUnitOfWork)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Users.Commands.AuthenticateUser.AuthenticateUserCommandHandler.#ctor(CoWorkingApp.Core.Contracts.Repositories.IUserRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Users.Queries.GetAllUsers.GetAllUsersQueryHandler.#ctor(CoWorkingApp.Core.Contracts.Repositories.IUserRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Users.Queries.GetUserByEmail.GetUserByEmailQueryHandler.#ctor(CoWorkingApp.Core.Contracts.Repositories.IUserRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Users.Queries.GetUserById.GetUserByIdQueryHandler.#ctor(CoWorkingApp.Core.Contracts.Repositories.IUserRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Seats.Commands.CreateSeat.CreateSeatCommandHandler.#ctor(CoWorkingApp.Core.Contracts.UnitOfWork.IUnitOfWork,CoWorkingApp.Core.Contracts.Repositories.ISeatRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Seats.Commands.DeleteSeat.DeleteSeatCommandHandler.#ctor(CoWorkingApp.Core.Contracts.UnitOfWork.IUnitOfWork,CoWorkingApp.Core.Contracts.Repositories.ISeatRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Seats.Commands.UpdateSeat.UpdateSeatCommandHandler.#ctor(CoWorkingApp.Core.Contracts.UnitOfWork.IUnitOfWork,CoWorkingApp.Core.Contracts.Repositories.ISeatRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Seats.Queries.GetAllSeats.GetAllSeatsQueryHandler.#ctor(CoWorkingApp.Core.Contracts.Repositories.ISeatRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Seats.Queries.GetSeatById.GetSeatByIdQueryHandler.#ctor(CoWorkingApp.Core.Contracts.Repositories.ISeatRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Seats.Queries.GetSeatByName.GetSeatByNameQueryHandler.#ctor(CoWorkingApp.Core.Contracts.Repositories.ISeatRepository)")]
[assembly: SuppressMessage("Style", "IDE0290:Usar constructor principal", Justification = "<pendiente>", Scope = "member", Target = "~M:CoWorkingApp.Application.Reservations.Queries.GetReservationsByUserEmail.GetReservationsByUserEmailQueryHandler.#ctor(CoWorkingApp.Core.Contracts.Repositories.IReservationRepository)")]
