<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" >
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" >
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
	<PackageReference Include="Moq" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoWorkingApp.API\CoWorkingApp.API.csproj" />
    <ProjectReference Include="..\CoWorkingApp.Application\CoWorkingApp.Application.csproj" />
    <ProjectReference Include="..\CoWorkingApp.Core\CoWorkingApp.Core.csproj" />
    <ProjectReference Include="..\CoWorkingApp.Infrastructure\CoWorkingApp.Infrastructure.csproj" />
    <ProjectReference Include="..\CoWorkingApp.Persistence\CoWorkingApp.Persistence.csproj" />
    <ProjectReference Include="..\CoWorkingApp.Presentation\CoWorkingApp.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\DTOs\" />
    <Folder Include="Presentation\Controllers\" />
    <Folder Include="Persistence\Repositories\" />
    <Folder Include="ClassData\" />
  </ItemGroup>

</Project>
