<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Asp.Versioning.Mvc" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" />
	<PackageReference Include="Microsoft.AspNetCore.OData" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
	<PackageReference Include="Scrutor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoWorkingApp.Application\CoWorkingApp.Application.csproj" />
    <ProjectReference Include="..\CoWorkingApp.Infrastructure\CoWorkingApp.Infrastructure.csproj" />
  </ItemGroup>

</Project>
